version: '3.8'
services:

  mongo_container:
    image: mongo:latest
    container_name: mongo_container
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod", "--bind_ip_all"]
    volumes:
      - ./mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_container:27017/mydatabase
      - SERVER_PORT=8081
    depends_on:
      mongo_container:
        condition: service_healthy

  library-service:
    build:
      context: ./libraryservice
      dockerfile: Dockerfile
    container_name: library-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo_container:27017/librarydb
      - SERVER_PORT=8082
    depends_on:
      mongo_container:
        condition: service_healthy

  gateway-service:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "8080:8080"
    environment:
      - GATEWAY_AUTH_SERVICE_URI=http://auth-service:8081
      - GATEWAY_LIBRARY_SERVICE_URI=http://library-service:8082
    depends_on:
      - auth-service
      - library-service

  frontend:
    build:
      context: ./library-app
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:8080
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - gateway-service